Vagrant::Config.run do |config|
config.vm.box = "dapper"
config.vm.forward_port 3000, 3000
config.vm.forward_port 9292, 9292
config.vm.forward_port 4000, 4000
config.ssh.forward_agent = true
config.vm.customize ["modifyvm", :id, "--memory", 1024]
end